source 'https://rubygems.org'

gem 'pry-byebug', '~> 2.0.0'
gem 'webdrivers', '~> 3.2'
gem 'watir'
gem 'configuration'
# gem 'sqlite3'
gem 'elasticsearch', '~> 7.0'
gem 'elastic-app-search', '~> 7.4.0'
gem 'pg'
gem 'aws-sdk', '~> 3'